In [1]:
import numpy as np
import os
import torch
import sys
sys.path.append("/data/nishome/user1/chaochuan/TSGym_benchmark")
from models.TSGym import Model as TSGym
print(torch.device("cuda" if torch.cuda.is_available() else "cpu"))

/data/nishome/user1/miniconda3/envs/mqenv/lib/python3.11/site-packages/local_attention/rotary.py:33: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  @autocast(enabled = False)
/data/nishome/user1/miniconda3/envs/mqenv/lib/python3.11/site-packages/local_attention/rotary.py:55: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  @autocast(enabled = False)

cuda

In [9]:
import sqlite3
import pandas as pd

dataset="ECL"
df = None
for dataset in ["ETTh1", "ETTh2", "ETTm1", "ETTm2", "ECL", "ECl", "Exchange", "ili", "nasdaq", "nyse", "weather", "traffic"]:
    DB_PATH = f"V100_log/long_term_forecast_SOTA_{dataset}_log.db"

    conn = sqlite3.connect(DB_PATH)
    temp_df = pd.read_sql_query("SELECT * FROM exp_logs", conn)
    conn.close()
    if df is None:
        df = temp_df
    else:
        df = pd.concat([df, temp_df], ignore_index=True)
df

,exp_setting,start_time,end_time,duration_sec,status,max_gpu_mem_MB,result_metric,error_msg
0,LTF_Autoformer_ETTh1_ftM_sl96_ll48_pl96_dm512_...,2026-01-06 10:32:19,None,NaN,RUNNING,NaN,None,None
1,LTF_Autoformer_ETTh1_ftM_sl96_ll48_pl192_dm512...,2026-01-06 10:32:34,None,NaN,RUNNING,NaN,None,None
2,LTF_Autoformer_ETTh1_ftM_sl96_ll48_pl336_dm512...,2026-01-06 10:32:41,None,NaN,RUNNING,NaN,None,None
3,LTF_Autoformer_ETTh1_ftM_sl96_ll48_pl720_dm512...,2026-01-06 10:32:48,2026-01-06 10:37:00,252.0,FINISHED,6512.0,"""file:ETTh1.csv, mse:0.5438016653060913, mae:0...",None
4,LTF_Crossformer_ETTh1_ftM_sl96_ll48_pl96_dm512...,2026-01-06 10:37:13,2026-01-06 10:38:20,67.0,FINISHED,1434.0,"""file:ETTh1.csv, mse:0.4095850884914398, mae:0...",None
...,...,...,...,...,...,...,...,...
861,LTF_DUET_traffic_ftM_sl96_ll48_pl192_dm512_el4...,2026-01-07 05:11:04,2026-01-07 05:11:18,14.0,FAILED,NaN,null,CUDA out of memory. Tried to allocate 4.34 GiB...
862,LTF_DUET_traffic_ftM_sl96_ll48_pl336_dm512_el4...,2026-01-07 05:11:24,2026-01-07 05:11:36,12.0,FAILED,NaN,null,CUDA out of memory. Tried to allocate 4.34 GiB...
863,LTF_DUET_traffic_ftM_sl96_ll48_pl720_dm512_el4...,2026-01-07 05:11:42,2026-01-07 05:11:50,8.0,FAILED,NaN,null,CUDA out of memory. Tried to allocate 4.34 GiB...
864,LTF_FiLM_traffic_ftM_sl720_ll48_pl96_dm512_el2...,2026-01-07 05:11:57,2026-01-07 11:38:22,23185.0,FINISHED,10544.0,"""file:traffic.csv, mse:0.4109334647655487, mae...",None
865,LTF_FiLM_traffic_ftM_sl720_ll48_pl192_dm512_el...,2026-01-07 11:38:36,None,NaN,RUNNING,NaN,None,None

In [10]:
df[df['status']=="FINISHED"].shape, df[df['status']=="FAILED"].shape, df[df['status']=="RUNNING"].shape

((798, 8), (56, 8), (12, 8))

In [19]:
df[(df['status'].str.contains("FAILED", regex=True, na=False)) & ~(df['error_msg'].str.contains("mamba", regex=False, na=False)) & ~(df['error_msg'].str.contains("CUDA", regex=False, na=False))]

,exp_setting,start_time,end_time,duration_sec,status,max_gpu_mem_MB,result_metric,error_msg
644,LTF_Crossformer_nasdaq_ftM_sl36_ll18_pl48_dm51...,2026-01-06 10:55:00,2026-01-06 10:55:01,1.0,FAILED,NaN,null,__len__() should return >= 0
648,LTF_DLinear_nasdaq_ftM_sl36_ll18_pl48_dm512_el...,2026-01-06 10:55:51,2026-01-06 10:55:51,0.0,FAILED,NaN,null,__len__() should return >= 0
662,LTF_SegRNN_nasdaq_ftM_sl36_ll48_pl24_dm512_el2...,2026-01-06 10:59:43,2026-01-06 10:59:44,1.0,FAILED,NaN,null,"Expected hidden size (1, 160, 512), got [1, 24..."
663,LTF_SegRNN_nasdaq_ftM_sl36_ll48_pl36_dm512_el2...,2026-01-06 10:59:51,2026-01-06 10:59:51,0.0,FAILED,NaN,null,"Expected hidden size (1, 160, 512), got [1, 24..."
664,LTF_SegRNN_nasdaq_ftM_sl36_ll48_pl48_dm512_el2...,2026-01-06 10:59:58,2026-01-06 10:59:59,1.0,FAILED,NaN,null,"Expected hidden size (1, 320, 512), got [1, 48..."
665,LTF_SegRNN_nasdaq_ftM_sl36_ll48_pl60_dm512_el2...,2026-01-06 11:00:09,2026-01-06 11:00:09,0.0,FAILED,NaN,null,"stack expects each tensor to be equal size, bu..."
666,LTF_TimeMixer_nasdaq_ftM_sl36_ll0_pl24_dm16_el...,2026-01-06 11:00:17,2026-01-06 11:00:17,0.0,FAILED,NaN,null,The size of tensor a (4) must match the size o...
667,LTF_TimeMixer_nasdaq_ftM_sl36_ll0_pl36_dm16_el...,2026-01-06 11:00:24,2026-01-06 11:00:25,1.0,FAILED,NaN,null,The size of tensor a (4) must match the size o...
668,LTF_TimeMixer_nasdaq_ftM_sl36_ll0_pl48_dm16_el...,2026-01-06 11:00:32,2026-01-06 11:00:32,0.0,FAILED,NaN,null,The size of tensor a (4) must match the size o...
669,LTF_TimeMixer_nasdaq_ftM_sl36_ll0_pl60_dm16_el...,2026-01-06 11:00:39,2026-01-06 11:00:40,1.0,FAILED,NaN,null,The size of tensor a (4) must match the size o...
756,LTF_Crossformer_nyse_ftM_sl36_ll18_pl48_dm512_...,2026-01-06 10:47:57,2026-01-06 10:47:58,1.0,FAILED,NaN,null,__len__() should return >= 0
760,LTF_DLinear_nyse_ftM_sl36_ll18_pl48_dm512_el2_...,2026-01-06 10:48:35,2026-01-06 10:48:35,0.0,FAILED,NaN,null,__len__() should return >= 0
774,LTF_SegRNN_nyse_ftM_sl36_ll48_pl24_dm512_el2_d...,2026-01-06 10:51:50,2026-01-06 10:51:51,1.0,FAILED,NaN,null,"Expected hidden size (1, 160, 512), got [1, 24..."
775,LTF_SegRNN_nyse_ftM_sl36_ll48_pl36_dm512_el2_d...,2026-01-06 10:51:57,2026-01-06 10:51:57,0.0,FAILED,NaN,null,"Expected hidden size (1, 160, 512), got [1, 24..."
776,LTF_SegRNN_nyse_ftM_sl36_ll48_pl48_dm512_el2_d...,2026-01-06 10:52:03,2026-01-06 10:52:03,0.0,FAILED,NaN,null,"Expected hidden size (1, 320, 512), got [1, 48..."
777,LTF_SegRNN_nyse_ftM_sl36_ll48_pl60_dm512_el2_d...,2026-01-06 10:52:09,2026-01-06 10:52:09,0.0,FAILED,NaN,null,"Expected hidden size (1, 320, 512), got [1, 48..."
778,LTF_TimeMixer_nyse_ftM_sl36_ll0_pl24_dm16_el2_...,2026-01-06 10:52:18,2026-01-06 10:52:19,1.0,FAILED,NaN,null,The size of tensor a (4) must match the size o...
779,LTF_TimeMixer_nyse_ftM_sl36_ll0_pl36_dm16_el2_...,2026-01-06 10:52:25,2026-01-06 10:52:26,1.0,FAILED,NaN,null,The size of tensor a (4) must match the size o...
780,LTF_TimeMixer_nyse_ftM_sl36_ll0_pl48_dm16_el2_...,2026-01-06 10:52:32,2026-01-06 10:52:33,1.0,FAILED,NaN,null,The size of tensor a (4) must match the size o...
781,LTF_TimeMixer_nyse_ftM_sl36_ll0_pl60_dm16_el2_...,2026-01-06 10:52:39,2026-01-06 10:52:39,0.0,FAILED,NaN,null,The size of tensor a (4) must match the size o...

In [18]:
df[(df['status'].str.contains("FAILED", regex=True)) & (df['error_msg'].str.contains("CUDA", regex=True))]

,exp_setting,start_time,end_time,duration_sec,status,max_gpu_mem_MB,result_metric,error_msg
426,LTF_Crossformer_ECL_ftM_sl96_ll48_pl720_dm256_...,2026-01-06 14:59:53,2026-01-06 14:59:57,4.0,FAILED,NaN,null,CUDA out of memory. Tried to allocate 302.00 M...
475,LTF_DUET_ECl_ftM_sl512_ll48_pl96_dm512_el4_dl1...,2026-01-06 15:04:09,2026-01-06 18:06:50,10961.0,FAILED,NaN,null,Attempting to deserialize object on CUDA devic...
858,LTF_Crossformer_traffic_ftM_sl96_ll96_pl720_dm...,2026-01-07 05:09:57,2026-01-07 05:10:04,7.0,FAILED,NaN,null,CUDA out of memory. Tried to allocate 1.58 GiB...
859,LTF_DUET_traffic_ftM_sl336_ll48_pl96_dm512_el4...,2026-01-07 05:10:11,2026-01-07 05:10:19,8.0,FAILED,NaN,null,CUDA out of memory. Tried to allocate 7.49 GiB...
860,LTF_DUET_traffic_ftM_sl96_ll48_pl96_dm512_el4_...,2026-01-07 05:10:26,2026-01-07 05:10:55,29.0,FAILED,NaN,null,CUDA out of memory. Tried to allocate 4.34 GiB...
861,LTF_DUET_traffic_ftM_sl96_ll48_pl192_dm512_el4...,2026-01-07 05:11:04,2026-01-07 05:11:18,14.0,FAILED,NaN,null,CUDA out of memory. Tried to allocate 4.34 GiB...
862,LTF_DUET_traffic_ftM_sl96_ll48_pl336_dm512_el4...,2026-01-07 05:11:24,2026-01-07 05:11:36,12.0,FAILED,NaN,null,CUDA out of memory. Tried to allocate 4.34 GiB...
863,LTF_DUET_traffic_ftM_sl96_ll48_pl720_dm512_el4...,2026-01-07 05:11:42,2026-01-07 05:11:50,8.0,FAILED,NaN,null,CUDA out of memory. Tried to allocate 4.34 GiB...

In [14]:
df[(df['exp_setting'].str.contains(f"True_{dataset}", regex=True))]

,exp_setting,start_time,end_time,duration_sec,status,max_gpu_mem_MB,result_metric,error_msg
8,LTF_TSGym1000324_True_False_RevIN_DFT_False_se...,2026-01-05 04:53:05,2026-01-05 04:53:09,4.0,FAILED,NaN,null,CUDA out of memory. Tried to allocate 3.15 GiB...
9,LTF_TSGym1000324_True_False_RevIN_DFT_False_se...,2026-01-05 04:53:17,2026-01-05 04:53:21,4.0,FAILED,NaN,null,CUDA out of memory. Tried to allocate 3.13 GiB...
10,LTF_TSGym1000324_True_False_RevIN_DFT_False_se...,2026-01-05 04:53:28,2026-01-05 04:53:33,5.0,FAILED,NaN,null,CUDA out of memory. Tried to allocate 3.11 GiB...
11,LTF_TSGym1000324_True_False_RevIN_DFT_False_se...,2026-01-05 04:53:40,2026-01-05 04:53:44,4.0,FAILED,NaN,null,CUDA out of memory. Tried to allocate 3.04 GiB...
33,LTF_TSGym1000341_True_False_RevIN_MA_True_seri...,2026-01-05 10:18:20,None,NaN,RUNNING,NaN,None,None
34,LTF_TSGym1000299_True_False_None_MA_True_serie...,2026-01-05 10:18:27,None,NaN,RUNNING,NaN,None,None
35,LTF_TSGym1000341_True_False_RevIN_MA_True_seri...,2026-01-05 10:21:06,None,NaN,RUNNING,NaN,None,None
37,LTF_TSGym1000299_True_False_None_MA_True_serie...,2026-01-05 10:22:01,None,NaN,RUNNING,NaN,None,None
38,LTF_TSGym1000341_True_False_RevIN_MA_True_seri...,2026-01-05 10:23:28,None,NaN,RUNNING,NaN,None,None
39,LTF_TSGym1000299_True_False_None_MA_True_serie...,2026-01-05 10:25:40,None,NaN,RUNNING,NaN,None,None
40,LTF_TSGym1000341_True_False_RevIN_MA_True_seri...,2026-01-05 10:26:05,None,NaN,RUNNING,NaN,None,None
42,LTF_TSGym1000299_True_False_None_MA_True_serie...,2026-01-05 10:27:59,None,NaN,RUNNING,NaN,None,None
50,LTF_TSGym1000124_False_False_RevIN_None_False_...,2026-01-05 11:09:57,2026-01-05 11:10:39,42.0,FAILED,NaN,null,index 2537 is out of bounds for dimension 0 wi...
51,LTF_TSGym1000124_False_False_RevIN_None_False_...,2026-01-05 11:10:47,2026-01-05 11:11:42,55.0,FAILED,NaN,null,index 2453 is out of bounds for dimension 0 wi...
52,LTF_TSGym1000124_False_False_RevIN_None_False_...,2026-01-05 11:11:51,2026-01-05 11:13:11,80.0,FAILED,NaN,null,index 2301 is out of bounds for dimension 0 wi...
53,LTF_TSGym1000124_False_False_RevIN_None_False_...,2026-01-05 11:13:21,2026-01-05 11:13:27,6.0,FAILED,NaN,null,CUDA out of memory. Tried to allocate 15.19 Gi...
62,LTF_TSGym1000335_True_False_RevIN_MA_False_ser...,2026-01-05 11:55:07,2026-01-05 11:55:44,37.0,FAILED,NaN,null,index 2557 is out of bounds for dimension 0 wi...
63,LTF_TSGym1000335_True_False_RevIN_MA_False_ser...,2026-01-05 11:55:52,2026-01-05 11:56:44,52.0,FAILED,NaN,null,index 2447 is out of bounds for dimension 0 wi...
64,LTF_TSGym1000335_True_False_RevIN_MA_False_ser...,2026-01-05 11:56:52,2026-01-05 11:58:11,79.0,FAILED,NaN,null,index 2298 is out of bounds for dimension 0 wi...
65,LTF_TSGym1000335_True_False_RevIN_MA_False_ser...,2026-01-05 11:58:21,2026-01-05 11:58:26,5.0,FAILED,NaN,null,CUDA out of memory. Tried to allocate 15.15 Gi...

In [33]:
import sqlite3
import pandas as pd

dataset="Exchange"

DB_PATH = f"../long_term_forecast_SOTA_{dataset}_log.db"

conn = sqlite3.connect(DB_PATH)
df = pd.read_sql_query("SELECT * FROM exp_logs", conn)
conn.close()
df

,exp_setting,start_time,end_time,duration_sec,status,max_gpu_mem_MB,result_metric,error_msg
0,LTF_CrossCrossModel_Exchange_ftM_sl96_ll48_pl9...,2026-01-06 20:06:11,2026-01-06 20:06:39,28.0,FINISHED,490.0,"""file:exchange_rate.csv, mse:0.085512906312942...",None
1,LTF_CrossCrossModel_Exchange_ftM_sl96_ll48_pl1...,2026-01-06 20:06:48,2026-01-06 20:07:15,27.0,FINISHED,490.0,"""file:exchange_rate.csv, mse:0.179240271449089...",None
2,LTF_CrossCrossModel_Exchange_ftM_sl96_ll48_pl3...,2026-01-06 20:07:23,2026-01-06 20:07:32,9.0,FINISHED,576.0,"""file:exchange_rate.csv, mse:0.334074467420578...",None
3,LTF_CrossCrossModel_Exchange_ftM_sl96_ll48_pl7...,2026-01-06 20:07:41,2026-01-06 20:08:14,33.0,FINISHED,670.0,"""file:exchange_rate.csv, mse:0.866330444812774...",None

In [9]:
def get_log_df(db_path):
    import sqlite3
    import pandas as pd

    conn = sqlite3.connect(db_path)
    df = pd.read_sql_query("SELECT * FROM exp_logs", conn)
    conn.close()
    return df

In [32]:
import os
import warnings
warnings.filterwarnings("ignore")
DB_PATH_LIST = [x for x in os.listdir("../") if "SOTA" in x and x.endswith("_log.db")]
log_df_list = [get_log_df(os.path.join("../", db_path)) for db_path in DB_PATH_LIST]
full_log_df = pd.concat(log_df_list, ignore_index=True)
full_log_df_CCModel = full_log_df[full_log_df['exp_setting'].str.contains("CrossCrossModel", regex=True)]
full_log_df_CCModel['dataset'] = full_log_df_CCModel['exp_setting'].apply(lambda x: x.split("_")[2])
full_log_df_CCModel['pred_len'] = full_log_df_CCModel['exp_setting'].apply(lambda x: x.split("_")[6])
full_log_df_CCModel['mse'] = full_log_df_CCModel['result_metric'].apply(lambda x: round(float(x.split("mse:")[1].split(",")[0]), 3) if pd.notna(x) else None)
full_log_df_CCModel['mae'] = full_log_df_CCModel['result_metric'].apply(lambda x: round(float(x.split("mae:")[1].split(",")[0]), 3) if pd.notna(x) else None)
full_log_df_CCModel[['dataset', 'mse', 'mae']].groupby(['dataset']).mean()

              mse      mae
dataset
ECL           NaN      NaN
ETTh1     0.46325  0.45400
ETTh2     0.37525  0.40225
ETTm1     0.39775  0.40800
ETTm2     0.29700  0.34000
Exchange  0.36625  0.40725
ili       2.07875  0.90175
weather   0.17900  0.22200

In [26]:
sota_result = pd.read_excel("./SOTA_result.xlsx")

In [28]:
sota_result.fillna(method="ffill", inplace=True)

In [29]:
sota_result

,Unnamed: 0,Unnamed: 1,DUET,Unnamed: 3,TimeMixer,Unnamed: 5,TSMixer,Unnamed: 7,MICN,Unnamed: 9,...,LightTS,Unnamed: 45,Informer,Unnamed: 47,Transformer,Unnamed: 49,Reformer,Unnamed: 51,CrossCrossModel,Unnamed: 53
0,NaN,NaN,mse,mae,mse,mae,mse,mae,mse,mae,...,mse,mae,mse,mae,mse,mae,mse,mae,mse,mae
1,dataset,pred_len,mse,mae,mse,mae,mse,mae,mse,mae,...,mse,mae,mse,mae,mse,mae,mse,mae,mse,mae
2,ETTm1,96,0.2929,0.3426,0.324,0.365,0.4894,0.4727,0.3206,0.3728,...,0.3603,0.3948,0.7418,0.6484,0.5051,0.4892,0.8972,0.6693,mse,mae
3,ETTm1,192,0.403,0.4034,0.3694,0.387,0.4744,0.4802,0.3685,0.4058,...,0.404,0.4193,0.893,0.7039,0.7589,0.6487,0.9136,0.6835,mse,mae
4,ETTm1,336,0.4277,0.4219,0.3915,0.4057,0.5374,0.5284,0.423,0.4488,...,0.4455,0.4507,1.0328,0.7749,1.0449,0.7919,1.0329,0.7461,mse,mae
5,ETTm1,720,0.5056,0.4691,0.4528,0.439,0.6059,0.5682,0.4953,0.4895,...,0.5423,0.5146,1.2065,0.8176,1.0352,0.7825,1.15,0.7931,mse,mae
6,ETTm1,Avg,0.407,0.409,0.384,0.399,0.527,0.512,0.402,0.429,...,0.438,0.445,0.969,0.736,0.836,0.678,0.998,0.723,mse,mae
7,ETTm2,96,0.1687,0.2553,0.1743,0.258,0.2533,0.3654,0.1854,0.2821,...,0.2254,0.3201,0.4915,0.5598,0.4297,0.468,0.7668,0.656,mse,mae
8,ETTm2,192,0.252,0.3119,0.2398,0.3001,0.4695,0.5327,0.2694,0.344,...,0.3261,0.3921,0.6148,0.6163,0.841,0.683,1.5306,0.9301,mse,mae
9,ETTm2,336,0.3276,0.3604,0.2982,0.3422,0.9014,0.7605,0.4008,0.4343,...,0.4954,0.4919,1.5991,0.9748,1.3972,0.9106,2.1139,1.0871,mse,mae
10,ETTm2,720,0.4346,0.4225,0.3959,0.399,2.4974,1.3411,0.5111,0.502,...,0.6806,0.5868,3.3095,1.3595,3.1472,1.3429,3.0135,1.3088,mse,mae
11,ETTm2,Avg,0.296,0.338,0.277,0.325,1.03,0.75,0.342,0.391,...,0.432,0.448,1.504,0.878,1.454,0.851,1.856,0.996,mse,mae
12,ETTh1,96,0.3559,0.3873,0.3816,0.3991,0.4827,0.4933,0.4114,0.4301,...,0.4489,0.4516,0.8878,0.7115,0.8547,0.7233,0.8592,0.6747,mse,mae
13,ETTh1,192,0.4172,0.4219,0.44,0.434,0.5709,0.5483,0.5152,0.4864,...,0.4994,0.4806,0.9786,0.7607,0.8463,0.721,0.9283,0.7182,mse,mae
14,ETTh1,336,0.4232,0.4359,0.4939,0.4526,0.6664,0.608,0.6196,0.5629,...,0.5517,0.5122,1.1539,0.837,1.0039,0.8165,0.9499,0.7367,mse,mae
15,ETTh1,720,0.5339,0.5036,0.4759,0.4671,0.7384,0.6672,0.8083,0.6696,...,0.6218,0.5749,1.2078,0.8841,1.0136,0.8107,1.1539,0.8281,mse,mae
16,ETTh1,Avg,0.433,0.437,0.448,0.438,0.615,0.579,0.589,0.537,...,0.53,0.505,1.057,0.798,0.93,0.768,0.973,0.739,mse,mae
17,ETTh2,96,0.2899,0.3464,0.2911,0.3421,1.1063,0.837,0.3798,0.4192,...,0.3937,0.4319,2.7607,1.3251,2.1369,1.1633,1.8541,1.0983,mse,mae
18,ETTh2,192,0.3788,0.3965,0.3789,0.3955,2.5688,1.379,0.4964,0.485,...,0.5147,0.4982,6.698,2.1543,3.8919,1.5663,2.5452,1.288,mse,mae
19,ETTh2,336,0.4213,0.4284,0.4244,0.4344,2.5433,1.3563,0.6283,0.5565,...,0.6664,0.5746,4.8315,1.8132,3.1086,1.3695,2.5657,1.2564,mse,mae
20,ETTh2,720,0.4288,0.4401,0.4372,0.4517,2.4228,1.3066,0.8366,0.6584,...,0.9565,0.7005,3.8486,1.6857,2.7661,1.3752,2.984,1.311,mse,mae
21,ETTh2,Avg,0.38,0.403,0.383,0.406,2.16,1.22,0.585,0.53,...,0.633,0.551,4.535,1.745,2.976,1.369,2.487,1.238,mse,mae
22,ECL,96,0.1552,0.238,0.1567,0.2484,0.2005,0.3071,0.1703,0.283,...,0.2142,0.3185,0.3395,0.4191,0.2576,0.3566,0.2974,0.3847,mse,mae
23,ECL,192,0.1686,0.25,0.1688,0.258,0.2159,0.3278,0.1738,0.2854,...,0.227,0.331,0.3667,0.4445,0.2719,0.37,0.338,0.4155,mse,mae
24,ECL,336,0.182,0.2674,0.1872,0.2765,0.2349,0.3476,0.1881,0.2995,...,0.2481,0.3506,0.3787,0.4541,0.2797,0.3722,0.3489,0.4229,mse,mae
25,ECL,720,0.2092,0.2935,0.2265,0.309,0.2646,0.3672,0.2134,0.3204,...,0.2814,0.3744,0.3917,0.4567,0.2814,0.3687,0.3136,0.3925,mse,mae
26,ECL,Avg,0.179,0.262,0.185,0.273,0.229,0.337,0.186,0.297,...,0.243,0.344,0.369,0.444,0.273,0.367,0.324,0.404,mse,mae
27,Traffic,96,0.3598,0.2376,0.4692,0.3032,0.5652,0.3807,0.5167,0.3099,...,0.6117,0.4048,0.7385,0.4156,0.648,0.3571,0.7003,0.3901,mse,mae
28,Traffic,192,1.8189,0.9293,0.4824,0.3069,0.5722,0.3909,0.537,0.3191,...,0.637,0.4213,0.7528,0.4227,0.705,0.3798,0.6927,0.3807,mse,mae
29,Traffic,336,0.4693,0.2586,0.502,0.3142,0.5999,0.4077,0.5467,0.3213,...,0.6599,0.4316,0.8655,0.4846,0.6813,0.3681,0.6902,0.3745,mse,mae
30,Traffic,720,0.5398,0.281,0.5311,0.3289,0.6594,0.4345,0.5738,0.3314,...,0.7168,0.4539,0.9614,0.5324,0.7994,0.4297,0.6936,0.3754,mse,mae
31,Traffic,Avg,0.797,0.427,0.496,0.313,0.599,0.403,0.544,0.32,...,0.656,0.428,0.83,0.464,0.708,0.384,0.694,0.38,mse,mae
32,Weather,96,0.1548,0.2011,0.1626,0.2096,0.1788,0.2486,0.1913,0.2486,...,0.1702,0.2316,0.3302,0.3938,0.3733,0.4116,0.3776,0.4037,mse,mae
33,Weather,192,0.2236,0.2551,0.2086,0.2521,0.2142,0.2836,0.2376,0.3001,...,0.2146,0.2744,0.4059,0.4286,0.5417,0.5083,0.4055,0.4281,mse,mae
34,Weather,336,0.2818,0.2992,0.2615,0.2897,0.2599,0.3161,0.28,0.3281,...,0.2634,0.3129,0.5411,0.5186,0.5637,0.5097,0.5854,0.5478,mse,mae
35,Weather,720,0.3478,0.3516,0.3435,0.344,0.3165,0.357,0.3453,0.3866,...,0.3303,0.3629,1.009,0.7491,0.9157,0.6961,0.5317,0.5087,mse,mae
36,Weather,Avg,0.252,0.277,0.244,0.274,0.242,0.301,0.264,0.316,...,0.245,0.295,0.572,0.523,0.599,0.531,0.475,0.472,mse,mae
37,Exchange,96,0.08,0.1985,0.0836,0.2009,0.2092,0.3584,0.093,0.2269,...,0.1331,0.2742,0.9407,0.7952,0.5878,0.6064,1.0923,0.8541,mse,mae
38,Exchange,192,0.1612,0.2885,0.1741,0.2968,0.4193,0.5109,0.1868,0.3331,...,0.2978,0.4057,1.1216,0.8719,1.103,0.8255,1.5666,1.0384,mse,mae
39,Exchange,336,0.3152,0.4088,0.3288,0.4155,0.7374,0.6993,0.3099,0.436,...,0.4826,0.5219,1.5547,1.0075,1.6593,1.038,1.9489,1.1442,mse,mae
40,Exchange,720,0.7333,0.6403,0.8484,0.6945,0.5829,0.615,0.7933,0.6922,...,1.0308,0.772,2.574,1.3125,2.1655,1.2159,1.8384,1.1388,mse,mae
41,Exchange,Avg,0.322,0.384,0.359,0.402,0.487,0.546,0.346,0.422,...,0.486,0.493,1.548,0.997,1.379,0.921,1.612,1.044,mse,mae
42,ILI,96,2.9996,1.0507,4.9236,1.6707,5.0365,1.5978,3.4087,1.2843,...,7.0727,1.9951,5.0041,1.5064,4.5079,1.4098,3.9094,1.289,mse,mae
43,ILI,192,2.8233,1.0616,4.5325,1.5712,4.9504,1.5618,2.6274,1.1019,...,6.9283,1.9653,5.0653,1.5613,4.4325,1.4096,4.0814,1.33,mse,mae
44,ILI,336,2.4862,1.0091,4.2795,1.4971,6.0777,1.7568,2.7387,1.1364,...,7.184,1.9764,4.9745,1.5367,4.7136,1.4516,4.361,1.3744,mse,mae
45,ILI,720,2.2497,0.9495,4.271,1.4894,6.4026,1.803,2.9754,1.1895,...,7.1276,1.9638,5.0969,1.5526,5.072,1.5222,4.4912,1.4078,mse,mae
46,ILI,Avg,2.64,1.018,4.502,1.557,5.617,1.68,2.938,1.178,...,7.078,1.975,5.035,1.539,4.682,1.448,4.211,1.35,mse,mae